service: detobit-auth
useDotenv: true

custom:
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 128
  versionFunctions: false
  lambdaHashingVersion: 20201221
  environment: ${file(./${self:custom.stage}.env.json)}
  apiGateway:
    apiKeys:
      - free:
          - ${opt:stage}-freekey
    usagePlan:
      - free:
          quota:
            limit: 5000
            period: MONTH
          throttle:
            burstLimit: 200
            rateLimit: 100

functions:
  auth:
    handler: src/handlers/auth.auth
    events:
      - http:
          path: auth
          method: post
          cors: true
          private: true
  signup:
    handler: src/handlers/singup.singup
    events:
      - http:
          path: singup
          method: post
          cors: true
          private: true

plugins:
- serverless-offline